table Region
lineageTag: e9096c9c-3d95-4339-84d7-3d3d7e9ff10d

column 'Region ID'
dataType: string
isHidden
isKey
lineageTag: 67f9ebeb-a9b4-43b4-89fe-b52e5a564f5a
summarizeBy: none
sourceColumn: region_id

annotation SummarizationSetBy = Automatic

column 'Region Name'
dataType: string
lineageTag: c22c0706-8fd8-4647-8fb2-9f38b5341384
summarizeBy: none
sourceColumn: region_name

annotation SummarizationSetBy = Automatic

partition Region = m
mode: import
source =
let
    Source = Csv.Document(File.Contents(DataFolder & "\\region_dim.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Promoted, {{"region_id", type text}, {"region_name", type text}})
in
    Typed
