table Segment
lineageTag: e7b2fb8d-cc53-4533-bf8d-f4261de01628

column 'Segment ID'
dataType: string
isHidden
isKey
lineageTag: ddc19a84-a666-4bd4-bd74-4b0941bd8566
summarizeBy: none
sourceColumn: segment_id

annotation SummarizationSetBy = Automatic

column 'Segment Name'
dataType: string
lineageTag: 1eca2f08-f684-460b-8186-b68f1c51595b
summarizeBy: none
sourceColumn: segment_name

annotation SummarizationSetBy = Automatic

partition Segment = m
mode: import
source =
let
    Source = Csv.Document(File.Contents(DataFolder & "\\segment_dim.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Promoted, {{"segment_id", type text}, {"segment_name", type text}})
in
    Typed
